# Generated by Django 5.2.6 on 2025-09-11 06:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0002_category_product_is_active_alter_product_tags_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MysteryBox',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('slug', models.SlugField(unique=True)),
                ('description', models.TextField(blank=True)),
                ('price_cop', models.PositiveIntegerField()),
                ('is_active', models.BooleanField(default=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='boxes/')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='mystery_boxes', to='catalog.category')),
            ],
        ),
    ]
