# Generated by Django 5.2.6 on 2025-09-12 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_category_product_is_active_alter_product_tags_and_more'),
        ('mistery_boxes', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mysterybox',
            name='category',
        ),
        migrations.AddField(
            model_name='mysterybox',
            name='products',
            field=models.ManyToManyField(related_name='mystery_boxes', to='catalog.product'),
        ),
    ]
