# Generated by Django 5.2.8 on 2025-11-06 16:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_category_product_is_active_alter_product_tags_and_more'),
        ('mistery_boxes', '0002_remove_mysterybox_category_mysterybox_products'),
    ]

    operations = [
        migrations.AddField(
            model_name='mysterybox',
            name='category',
            field=models.ForeignKey(blank=True, help_text='Categoría principal de esta caja misteriosa', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='mystery_boxes', to='catalog.category'),
        ),
    ]
