# Generated by Django 5.2.8 on 2025-11-06 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mistery_boxes', '0003_mysterybox_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mysterybox',
            name='image',
            field=models.ImageField(blank=True, default='mystery_boxes/default.png', null=True, upload_to='mystery_boxes/'),
        ),
    ]
