# Generated by Django 5.2.8 on 2025-11-06 17:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_alter_product_image'),
        ('orders', '0002_order_orderitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='is_mystery_box',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='mystery_box_id',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='won_product',
            field=models.ForeignKey(blank=True, help_text='Si este item es una mystery box, este campo indica qué producto se ganó', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='won_in_orders', to='catalog.product'),
        ),
    ]
